/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types.js"
import type {  BatchResult,  BoundingBox,  ContainerHealth,  CustomPrompts,  JobStatus,  OCRMetadata,  OCRResult,  PageMetadata,  PageResult,  PageStructure,  ProcessingOptions,  SystemHealth,  TextBlock } from "./types.js"
import type * as types from "./types.js"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface BatchResult {
      job_id?: string | null
      status?: types.JobStatus | null
      total_pages?: number | null
      pages_completed?: number | null
      progress_pct?: number | null
      page_results: PageResult[]
      error_message?: string | null
      started_at?: string | null
      completed_at?: string | null
    }
    export interface BoundingBox {
      x0?: number | null
      y0?: number | null
      x1?: number | null
      y1?: number | null
      page_width?: number | null
      page_height?: number | null
    }
    export interface ContainerHealth {
      status?: string | null
      model_loaded?: boolean | null
      gpu_available?: boolean | null
      memory_used_mb?: number | null
      memory_total_mb?: number | null
    }
    export interface CustomPrompts {
      ocr?: string | null
      merge?: string | null
      visual?: string | null
    }
    export interface OCRMetadata {
      container_mode?: boolean | null
      openai_compatible?: boolean | null
      image_width?: number | null
      image_height?: number | null
      char_count?: number | null
      word_count?: number | null
      has_visual_elements?: boolean | null
    }
    export interface OCRResult {
      text?: string | null
      model_name?: string | null
      processing_time?: number | null
      format?: string | null
      metadata?: OCRMetadata | null
    }
    export interface PageMetadata {
      embedded_text_length?: number | null
      ocr_text_length?: number | null
      merge_strategy?: string | null
      visual_formatting_applied?: boolean | null
      spatial_blocks_count?: number | null
      has_tables?: boolean | null
      has_images?: boolean | null
      dpi?: number | null
    }
    export interface PageResult {
      page_num?: number | null
      text?: string | null
      processing_method?: string | null
      processing_time?: number | null
      char_count?: number | null
      word_count?: number | null
      has_visual_elements?: boolean | null
      metadata?: PageMetadata | null
    }
    export interface PageStructure {
      page_num?: number | null
      width?: number | null
      height?: number | null
      text_blocks: TextBlock[]
      has_tables?: boolean | null
      has_images?: boolean | null
      column_count?: number | null
      reading_order?: number[] | null
    }
    export interface ProcessingOptions {
      method?: string | null
      enable_visual_formatting?: boolean | null
      spatial_awareness?: boolean | null
      table_detection?: boolean | null
      min_text_chars?: number | null
      dpi?: number | null
      custom_prompts?: CustomPrompts | null
    }
    export interface SystemHealth {
      deepseek?: ContainerHealth | null
      qwen?: ContainerHealth | null
      timestamp?: string | null
    }
    export interface TextBlock {
      text?: string | null
      bbox?: BoundingBox | null
      font_size?: number | null
      font_name?: string | null
      block_type?: string | null
      confidence?: number | null
    }
}