/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum JobStatus {
  Queued = "Queued",
  Processing = "Processing",
  Completed = "Completed",
  Failed = "Failed",
  Cancelled = "Cancelled",
}

export interface BatchResult {
  job_id: string
  status: JobStatus
  total_pages: number
  pages_completed: number
  progress_pct: number
  page_results: PageResult[]
  error_message?: string | null
  started_at?: string | null
  completed_at?: string | null
  
}

export interface BoundingBox {
  x0: number
  y0: number
  x1: number
  y1: number
  page_width: number
  page_height: number
  
}

export interface ContainerHealth {
  status: string
  model_loaded: boolean
  gpu_available: boolean
  memory_used_mb?: number | null
  memory_total_mb?: number | null
  
}

export interface CustomPrompts {
  ocr?: string | null
  merge?: string | null
  visual?: string | null
  
}

export interface OCRMetadata {
  container_mode: boolean
  openai_compatible: boolean
  image_width?: number | null
  image_height?: number | null
  char_count?: number | null
  word_count?: number | null
  has_visual_elements?: boolean | null
  
}

export interface OCRResult {
  text: string
  model_name: string
  processing_time: number
  format: string
  metadata?: OCRMetadata | null
  
}

export interface PageMetadata {
  embedded_text_length?: number | null
  ocr_text_length?: number | null
  merge_strategy?: string | null
  visual_formatting_applied?: boolean | null
  spatial_blocks_count?: number | null
  has_tables?: boolean | null
  has_images?: boolean | null
  dpi?: number | null
  
}

export interface PageResult {
  page_num: number
  text: string
  processing_method: string
  processing_time: number
  char_count: number
  word_count: number
  has_visual_elements: boolean
  metadata?: PageMetadata | null
  
}

export interface PageStructure {
  page_num: number
  width: number
  height: number
  text_blocks: TextBlock[]
  has_tables: boolean
  has_images: boolean
  column_count?: number | null
  reading_order?: number[] | null
  
}

export interface ProcessingOptions {
  method?: string | null
  enable_visual_formatting?: boolean | null
  spatial_awareness?: boolean | null
  table_detection?: boolean | null
  min_text_chars?: number | null
  dpi?: number | null
  custom_prompts?: CustomPrompts | null
  
}

export interface SystemHealth {
  deepseek: ContainerHealth
  qwen: ContainerHealth
  timestamp: string
  
}

export interface TextBlock {
  text: string
  bbox: BoundingBox
  font_size?: number | null
  font_name?: string | null
  block_type: string
  confidence?: number | null
  
}
