/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals.js"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    BatchResult: ClassViewer<'BatchResult', "job_id" | "status" | "total_pages" | "pages_completed" | "progress_pct" | "page_results" | "error_message" | "started_at" | "completed_at">;
    
    BoundingBox: ClassViewer<'BoundingBox', "x0" | "y0" | "x1" | "y1" | "page_width" | "page_height">;
    
    ContainerHealth: ClassViewer<'ContainerHealth', "status" | "model_loaded" | "gpu_available" | "memory_used_mb" | "memory_total_mb">;
    
    CustomPrompts: ClassViewer<'CustomPrompts', "ocr" | "merge" | "visual">;
    
    OCRMetadata: ClassViewer<'OCRMetadata', "container_mode" | "openai_compatible" | "image_width" | "image_height" | "char_count" | "word_count" | "has_visual_elements">;
    
    OCRResult: ClassViewer<'OCRResult', "text" | "model_name" | "processing_time" | "format" | "metadata">;
    
    PageMetadata: ClassViewer<'PageMetadata', "embedded_text_length" | "ocr_text_length" | "merge_strategy" | "visual_formatting_applied" | "spatial_blocks_count" | "has_tables" | "has_images" | "dpi">;
    
    PageResult: ClassViewer<'PageResult', "page_num" | "text" | "processing_method" | "processing_time" | "char_count" | "word_count" | "has_visual_elements" | "metadata">;
    
    PageStructure: ClassViewer<'PageStructure', "page_num" | "width" | "height" | "text_blocks" | "has_tables" | "has_images" | "column_count" | "reading_order">;
    
    ProcessingOptions: ClassViewer<'ProcessingOptions', "method" | "enable_visual_formatting" | "spatial_awareness" | "table_detection" | "min_text_chars" | "dpi" | "custom_prompts">;
    
    SystemHealth: ClassViewer<'SystemHealth', "deepseek" | "qwen" | "timestamp">;
    
    TextBlock: ClassViewer<'TextBlock', "text" | "bbox" | "font_size" | "font_name" | "block_type" | "confidence">;
    
    
    JobStatus: EnumViewer<'JobStatus', "Queued" | "Processing" | "Completed" | "Failed" | "Cancelled">;
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "BatchResult","BoundingBox","ContainerHealth","CustomPrompts","OCRMetadata","OCRResult","PageMetadata","PageResult","PageStructure","ProcessingOptions","SystemHealth","TextBlock",
          ]),
          enums: new Set([
            "JobStatus",
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.BatchResult = this.tb.classViewer("BatchResult", [
          "job_id","status","total_pages","pages_completed","progress_pct","page_results","error_message","started_at","completed_at",
        ]);
        
        this.BoundingBox = this.tb.classViewer("BoundingBox", [
          "x0","y0","x1","y1","page_width","page_height",
        ]);
        
        this.ContainerHealth = this.tb.classViewer("ContainerHealth", [
          "status","model_loaded","gpu_available","memory_used_mb","memory_total_mb",
        ]);
        
        this.CustomPrompts = this.tb.classViewer("CustomPrompts", [
          "ocr","merge","visual",
        ]);
        
        this.OCRMetadata = this.tb.classViewer("OCRMetadata", [
          "container_mode","openai_compatible","image_width","image_height","char_count","word_count","has_visual_elements",
        ]);
        
        this.OCRResult = this.tb.classViewer("OCRResult", [
          "text","model_name","processing_time","format","metadata",
        ]);
        
        this.PageMetadata = this.tb.classViewer("PageMetadata", [
          "embedded_text_length","ocr_text_length","merge_strategy","visual_formatting_applied","spatial_blocks_count","has_tables","has_images","dpi",
        ]);
        
        this.PageResult = this.tb.classViewer("PageResult", [
          "page_num","text","processing_method","processing_time","char_count","word_count","has_visual_elements","metadata",
        ]);
        
        this.PageStructure = this.tb.classViewer("PageStructure", [
          "page_num","width","height","text_blocks","has_tables","has_images","column_count","reading_order",
        ]);
        
        this.ProcessingOptions = this.tb.classViewer("ProcessingOptions", [
          "method","enable_visual_formatting","spatial_awareness","table_detection","min_text_chars","dpi","custom_prompts",
        ]);
        
        this.SystemHealth = this.tb.classViewer("SystemHealth", [
          "deepseek","qwen","timestamp",
        ]);
        
        this.TextBlock = this.tb.classViewer("TextBlock", [
          "text","bbox","font_size","font_name","block_type","confidence",
        ]);
        
        
        this.JobStatus = this.tb.enumViewer("JobStatus", [
          "Queued","Processing","Completed","Failed","Cancelled",
        ]);
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}