# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (12)
# #########################################################################

class BatchResult(BaseModel):
    job_id: typing.Optional[str] = None
    status: typing.Optional[types.JobStatus] = None
    total_pages: typing.Optional[int] = None
    pages_completed: typing.Optional[int] = None
    progress_pct: typing.Optional[float] = None
    page_results: typing.List["PageResult"]
    error_message: typing.Optional[str] = None
    started_at: typing.Optional[str] = None
    completed_at: typing.Optional[str] = None

class BoundingBox(BaseModel):
    x0: typing.Optional[float] = None
    y0: typing.Optional[float] = None
    x1: typing.Optional[float] = None
    y1: typing.Optional[float] = None
    page_width: typing.Optional[float] = None
    page_height: typing.Optional[float] = None

class ContainerHealth(BaseModel):
    status: typing.Optional[str] = None
    model_loaded: typing.Optional[bool] = None
    gpu_available: typing.Optional[bool] = None
    memory_used_mb: typing.Optional[float] = None
    memory_total_mb: typing.Optional[float] = None

class CustomPrompts(BaseModel):
    ocr: typing.Optional[str] = None
    merge: typing.Optional[str] = None
    visual: typing.Optional[str] = None

class OCRMetadata(BaseModel):
    container_mode: typing.Optional[bool] = None
    openai_compatible: typing.Optional[bool] = None
    image_width: typing.Optional[int] = None
    image_height: typing.Optional[int] = None
    char_count: typing.Optional[int] = None
    word_count: typing.Optional[int] = None
    has_visual_elements: typing.Optional[bool] = None

class OCRResult(BaseModel):
    text: typing.Optional[str] = None
    model_name: typing.Optional[str] = None
    processing_time: typing.Optional[float] = None
    format: typing.Optional[str] = None
    metadata: typing.Optional["OCRMetadata"] = None

class PageMetadata(BaseModel):
    embedded_text_length: typing.Optional[int] = None
    ocr_text_length: typing.Optional[int] = None
    merge_strategy: typing.Optional[str] = None
    visual_formatting_applied: typing.Optional[bool] = None
    spatial_blocks_count: typing.Optional[int] = None
    has_tables: typing.Optional[bool] = None
    has_images: typing.Optional[bool] = None
    dpi: typing.Optional[int] = None

class PageResult(BaseModel):
    page_num: typing.Optional[int] = None
    text: typing.Optional[str] = None
    processing_method: typing.Optional[str] = None
    processing_time: typing.Optional[float] = None
    char_count: typing.Optional[int] = None
    word_count: typing.Optional[int] = None
    has_visual_elements: typing.Optional[bool] = None
    metadata: typing.Optional["PageMetadata"] = None

class PageStructure(BaseModel):
    page_num: typing.Optional[int] = None
    width: typing.Optional[float] = None
    height: typing.Optional[float] = None
    text_blocks: typing.List["TextBlock"]
    has_tables: typing.Optional[bool] = None
    has_images: typing.Optional[bool] = None
    column_count: typing.Optional[int] = None
    reading_order: typing.Optional[typing.List[int]] = None

class ProcessingOptions(BaseModel):
    method: typing.Optional[str] = None
    enable_visual_formatting: typing.Optional[bool] = None
    spatial_awareness: typing.Optional[bool] = None
    table_detection: typing.Optional[bool] = None
    min_text_chars: typing.Optional[int] = None
    dpi: typing.Optional[int] = None
    custom_prompts: typing.Optional["CustomPrompts"] = None

class SystemHealth(BaseModel):
    deepseek: typing.Optional["ContainerHealth"] = None
    qwen: typing.Optional["ContainerHealth"] = None
    timestamp: typing.Optional[str] = None

class TextBlock(BaseModel):
    text: typing.Optional[str] = None
    bbox: typing.Optional["BoundingBox"] = None
    font_size: typing.Optional[float] = None
    font_name: typing.Optional[str] = None
    block_type: typing.Optional[str] = None
    confidence: typing.Optional[float] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
