# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    def CheckContainerHealth(self, 
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.CheckContainerHealth(
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="CheckContainerHealth", args={
                
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractTextOCR(self, page_image: baml_py.Image,custom_prompt: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractTextOCR(page_image=page_image,custom_prompt=custom_prompt,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractTextOCR", args={
                "page_image": page_image,"custom_prompt": custom_prompt,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractTextOCRFallback(self, page_image: baml_py.Image,custom_prompt: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.OCRResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractTextOCRFallback(page_image=page_image,custom_prompt=custom_prompt,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractTextOCRFallback", args={
                "page_image": page_image,"custom_prompt": custom_prompt,
            })
            return typing.cast(types.OCRResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractVisualFormatting(self, page_image: baml_py.Image,base_text: str,spatial_data: types.PageStructure,custom_prompt: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.OCRResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractVisualFormatting(page_image=page_image,base_text=base_text,spatial_data=spatial_data,custom_prompt=custom_prompt,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractVisualFormatting", args={
                "page_image": page_image,"base_text": base_text,"spatial_data": spatial_data,"custom_prompt": custom_prompt,
            })
            return typing.cast(types.OCRResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def MergeTexts(self, page_image: baml_py.Image,embedded_text: str,ocr_text: str,custom_prompt: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.MergeTexts(page_image=page_image,embedded_text=embedded_text,ocr_text=ocr_text,custom_prompt=custom_prompt,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="MergeTexts", args={
                "page_image": page_image,"embedded_text": embedded_text,"ocr_text": ocr_text,"custom_prompt": custom_prompt,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    def MergeTextsStreaming(self, page_image: baml_py.Image,embedded_text: str,ocr_text: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.MergeTextsStreaming(page_image=page_image,embedded_text=embedded_text,ocr_text=ocr_text,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="MergeTextsStreaming", args={
                "page_image": page_image,"embedded_text": embedded_text,"ocr_text": ocr_text,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def CheckContainerHealth(self, 
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="CheckContainerHealth", args={
            
        })
        return baml_py.BamlSyncStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractTextOCR(self, page_image: baml_py.Image,custom_prompt: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractTextOCR", args={
            "page_image": page_image,"custom_prompt": custom_prompt,
        })
        return baml_py.BamlSyncStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractTextOCRFallback(self, page_image: baml_py.Image,custom_prompt: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.OCRResult, types.OCRResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractTextOCRFallback", args={
            "page_image": page_image,"custom_prompt": custom_prompt,
        })
        return baml_py.BamlSyncStream[stream_types.OCRResult, types.OCRResult](
          result,
          lambda x: typing.cast(stream_types.OCRResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.OCRResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractVisualFormatting(self, page_image: baml_py.Image,base_text: str,spatial_data: types.PageStructure,custom_prompt: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.OCRResult, types.OCRResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractVisualFormatting", args={
            "page_image": page_image,"base_text": base_text,"spatial_data": spatial_data,"custom_prompt": custom_prompt,
        })
        return baml_py.BamlSyncStream[stream_types.OCRResult, types.OCRResult](
          result,
          lambda x: typing.cast(stream_types.OCRResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.OCRResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def MergeTexts(self, page_image: baml_py.Image,embedded_text: str,ocr_text: str,custom_prompt: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="MergeTexts", args={
            "page_image": page_image,"embedded_text": embedded_text,"ocr_text": ocr_text,"custom_prompt": custom_prompt,
        })
        return baml_py.BamlSyncStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def MergeTextsStreaming(self, page_image: baml_py.Image,embedded_text: str,ocr_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="MergeTextsStreaming", args={
            "page_image": page_image,"embedded_text": embedded_text,"ocr_text": ocr_text,
        })
        return baml_py.BamlSyncStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def CheckContainerHealth(self, 
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="CheckContainerHealth", args={
            
        }, mode="request")
        return result
    def ExtractTextOCR(self, page_image: baml_py.Image,custom_prompt: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractTextOCR", args={
            "page_image": page_image,"custom_prompt": custom_prompt,
        }, mode="request")
        return result
    def ExtractTextOCRFallback(self, page_image: baml_py.Image,custom_prompt: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractTextOCRFallback", args={
            "page_image": page_image,"custom_prompt": custom_prompt,
        }, mode="request")
        return result
    def ExtractVisualFormatting(self, page_image: baml_py.Image,base_text: str,spatial_data: types.PageStructure,custom_prompt: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractVisualFormatting", args={
            "page_image": page_image,"base_text": base_text,"spatial_data": spatial_data,"custom_prompt": custom_prompt,
        }, mode="request")
        return result
    def MergeTexts(self, page_image: baml_py.Image,embedded_text: str,ocr_text: str,custom_prompt: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="MergeTexts", args={
            "page_image": page_image,"embedded_text": embedded_text,"ocr_text": ocr_text,"custom_prompt": custom_prompt,
        }, mode="request")
        return result
    def MergeTextsStreaming(self, page_image: baml_py.Image,embedded_text: str,ocr_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="MergeTextsStreaming", args={
            "page_image": page_image,"embedded_text": embedded_text,"ocr_text": ocr_text,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def CheckContainerHealth(self, 
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="CheckContainerHealth", args={
            
        }, mode="stream")
        return result
    def ExtractTextOCR(self, page_image: baml_py.Image,custom_prompt: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractTextOCR", args={
            "page_image": page_image,"custom_prompt": custom_prompt,
        }, mode="stream")
        return result
    def ExtractTextOCRFallback(self, page_image: baml_py.Image,custom_prompt: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractTextOCRFallback", args={
            "page_image": page_image,"custom_prompt": custom_prompt,
        }, mode="stream")
        return result
    def ExtractVisualFormatting(self, page_image: baml_py.Image,base_text: str,spatial_data: types.PageStructure,custom_prompt: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractVisualFormatting", args={
            "page_image": page_image,"base_text": base_text,"spatial_data": spatial_data,"custom_prompt": custom_prompt,
        }, mode="stream")
        return result
    def MergeTexts(self, page_image: baml_py.Image,embedded_text: str,ocr_text: str,custom_prompt: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="MergeTexts", args={
            "page_image": page_image,"embedded_text": embedded_text,"ocr_text": ocr_text,"custom_prompt": custom_prompt,
        }, mode="stream")
        return result
    def MergeTextsStreaming(self, page_image: baml_py.Image,embedded_text: str,ocr_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="MergeTextsStreaming", args={
            "page_image": page_image,"embedded_text": embedded_text,"ocr_text": ocr_text,
        }, mode="stream")
        return result
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))