# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.BatchResult": types.BatchResult,
    "stream_types.BatchResult": stream_types.BatchResult,

    "types.BoundingBox": types.BoundingBox,
    "stream_types.BoundingBox": stream_types.BoundingBox,

    "types.ContainerHealth": types.ContainerHealth,
    "stream_types.ContainerHealth": stream_types.ContainerHealth,

    "types.CustomPrompts": types.CustomPrompts,
    "stream_types.CustomPrompts": stream_types.CustomPrompts,

    "types.OCRMetadata": types.OCRMetadata,
    "stream_types.OCRMetadata": stream_types.OCRMetadata,

    "types.OCRResult": types.OCRResult,
    "stream_types.OCRResult": stream_types.OCRResult,

    "types.PageMetadata": types.PageMetadata,
    "stream_types.PageMetadata": stream_types.PageMetadata,

    "types.PageResult": types.PageResult,
    "stream_types.PageResult": stream_types.PageResult,

    "types.PageStructure": types.PageStructure,
    "stream_types.PageStructure": stream_types.PageStructure,

    "types.ProcessingOptions": types.ProcessingOptions,
    "stream_types.ProcessingOptions": stream_types.ProcessingOptions,

    "types.SystemHealth": types.SystemHealth,
    "stream_types.SystemHealth": stream_types.SystemHealth,

    "types.TextBlock": types.TextBlock,
    "stream_types.TextBlock": stream_types.TextBlock,


    "types.JobStatus": types.JobStatus,

}