# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class JobStatus(str, Enum):
    Queued = "Queued"
    Processing = "Processing"
    Completed = "Completed"
    Failed = "Failed"
    Cancelled = "Cancelled"

# #########################################################################
# Generated classes (12)
# #########################################################################

class BatchResult(BaseModel):
    job_id: str
    status: JobStatus
    total_pages: int
    pages_completed: int
    progress_pct: float
    page_results: typing.List["PageResult"]
    error_message: typing.Optional[str] = None
    started_at: typing.Optional[str] = None
    completed_at: typing.Optional[str] = None

class BoundingBox(BaseModel):
    x0: float
    y0: float
    x1: float
    y1: float
    page_width: float
    page_height: float

class ContainerHealth(BaseModel):
    status: str
    model_loaded: bool
    gpu_available: bool
    memory_used_mb: typing.Optional[float] = None
    memory_total_mb: typing.Optional[float] = None

class CustomPrompts(BaseModel):
    ocr: typing.Optional[str] = None
    merge: typing.Optional[str] = None
    visual: typing.Optional[str] = None

class OCRMetadata(BaseModel):
    container_mode: bool
    openai_compatible: bool
    image_width: typing.Optional[int] = None
    image_height: typing.Optional[int] = None
    char_count: typing.Optional[int] = None
    word_count: typing.Optional[int] = None
    has_visual_elements: typing.Optional[bool] = None

class OCRResult(BaseModel):
    text: str
    model_name: str
    processing_time: float
    format: str
    metadata: typing.Optional["OCRMetadata"] = None

class PageMetadata(BaseModel):
    embedded_text_length: typing.Optional[int] = None
    ocr_text_length: typing.Optional[int] = None
    merge_strategy: typing.Optional[str] = None
    visual_formatting_applied: typing.Optional[bool] = None
    spatial_blocks_count: typing.Optional[int] = None
    has_tables: typing.Optional[bool] = None
    has_images: typing.Optional[bool] = None
    dpi: typing.Optional[int] = None

class PageResult(BaseModel):
    page_num: int
    text: str
    processing_method: str
    processing_time: float
    char_count: int
    word_count: int
    has_visual_elements: bool
    metadata: typing.Optional["PageMetadata"] = None

class PageStructure(BaseModel):
    page_num: int
    width: float
    height: float
    text_blocks: typing.List["TextBlock"]
    has_tables: bool
    has_images: bool
    column_count: typing.Optional[int] = None
    reading_order: typing.Optional[typing.List[int]] = None

class ProcessingOptions(BaseModel):
    method: typing.Optional[str] = None
    enable_visual_formatting: typing.Optional[bool] = None
    spatial_awareness: typing.Optional[bool] = None
    table_detection: typing.Optional[bool] = None
    min_text_chars: typing.Optional[int] = None
    dpi: typing.Optional[int] = None
    custom_prompts: typing.Optional["CustomPrompts"] = None

class SystemHealth(BaseModel):
    deepseek: "ContainerHealth"
    qwen: "ContainerHealth"
    timestamp: str

class TextBlock(BaseModel):
    text: str
    bbox: "BoundingBox"
    font_size: typing.Optional[float] = None
    font_name: typing.Optional[str] = None
    block_type: str
    confidence: typing.Optional[float] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
